ckpt_path: null
data:
  class_path: ssg_tools.dataset.hetero_dataset.HomoSceneGraphModule
  init_args:
    batch_size: 64
    num_processes: 1
    num_workers: 32
    persistent_workers: true
    pin_memory: true
    root: /path/to/data/root
    scan_dir: null
    shuffle: true
    single_type: new
lr_scheduler:
  class_path: torch.optim.lr_scheduler.StepLR
  init_args:
    gamma: 0.05
    last_epoch: -1
    step_size: 30
    verbose: deprecated
model:
  class_path: ssg_tools.models.sgfn.SGFN
  init_args:
    batch_norm: true
    edge_descriptor_size: 11
    edge_feature_size: 256
    feature_transform: true
    gnn_aggr: max
    gnn_attention: fat
    gnn_dim_attention: 256
    gnn_drop_out_attention: 0.3
    gnn_n_attention_heads: 8
    gnn_n_layers: 2
    gnn_use_edge: true
    lambda_node: 0.1
    lr_scheduler: null
    multilabel_edges: true
    n_edge_classes: 16
    n_node_classes: 27
    node_feature_size: 256
    node_point_size: 3
    optimizer: null
    scheduler_frequency: 1
    scheduler_metric: val_loss
    sync_dist: false
    use_spatial: true
    weight_edge_mode: dynamic
    weighting: true
optimizer:
  class_path: torch.optim.Adam
  init_args:
    amsgrad: false
    betas:
    - 0.9
    - 0.999
    capturable: false
    differentiable: false
    eps: 1.0e-08
    foreach: null
    fused: null
    lr: 0.00014981950627824397
    maximize: false
    weight_decay: 0.0
seed_everything: 0
trainer:
  accelerator: auto
  accumulate_grad_batches: 1
  barebones: false
  benchmark: null
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      auto_insert_metric_name: true
      dirpath: null
      enable_version_counter: true
      every_n_epochs: null
      every_n_train_steps: null
      filename: last
      mode: max
      monitor: epoch
      save_last: null
      save_on_train_epoch_end: null
      save_top_k: 1
      save_weights_only: false
      train_time_interval: null
      verbose: false
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      check_finite: true
      check_on_train_epoch_end: null
      divergence_threshold: null
      log_rank_zero_only: false
      min_delta: 0.0
      mode: min
      monitor: val_loss
      patience: 5
      stopping_threshold: null
      strict: true
      verbose: false
  check_val_every_n_epoch: 1
  default_root_dir: null
  detect_anomaly: false
  deterministic: null
  devices: auto
  enable_checkpointing: null
  enable_model_summary: null
  enable_progress_bar: null
  fast_dev_run: false
  gradient_clip_algorithm: null
  gradient_clip_val: null
  inference_mode: true
  limit_predict_batches: null
  limit_test_batches: null
  limit_train_batches: null
  limit_val_batches: null
  log_every_n_steps: null
  logger: null
  max_epochs: 100
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  num_nodes: 1
  num_sanity_val_steps: null
  overfit_batches: 0.0
  plugins: null
  precision: null
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  strategy: ddp_find_unused_parameters_true
  sync_batchnorm: false
  use_distributed_sampler: true
  val_check_interval: null
